services:
  app-n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: app-n8n
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-n8n.rule=Host(`${N8N_HOST}`)
      - traefik.http.routers.app-n8n.tls=true
      - traefik.http.routers.app-n8n.tls.certresolver=letsencrypt
      - traefik.http.routers.app-n8n.entrypoints=web,websecure
      - traefik.http.routers.app-n8n.middlewares=redirect
      - traefik.http.middlewares.redirect.redirectscheme.scheme=${N8N_PROTOCOL}
      - traefik.http.services.app-n8n.loadbalancer.server.port=${N8N_PORT}
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=Europe/Istanbul
      - TZ=Europe/Istanbul
    volumes:
      - ./volumes/node/.n8n:/home/node/.n8n
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
    name: proxy

